---

- hosts: scrapy
  become: yes
  roles:
    - ansible-role-yum-repos
    - ansible-role-initialize
    - ansible-role-git
    - ansible-role-dotfiles
    - ansible-role-scrapy
    - ansible-role-java
    - ansible-role-elasticsearch
  vars:
    dotfile_users:
    - {
        name: root,
        dest: /root,
        gitname: GIT_ROOT_NAME,
        gitmail: ROOT@EMAIL
      }
    - {
        name: vagrant,
        dest: /home/vagrant,
        gitname: GIT_VAGRANT_NAME,
        gitmail: VAGRANT@EMAIL
      }
    elasticsearch_cluster_name: ansible-elastic-cluster
    elasticsearch_host: 192.168.33.100
    elasticsearch_kibana_host: 192.168.33.100
    elasticsearch_kibana_bind_url: "http://192.168.33.100:9200"
